[font]
size = 14.0

[font.bold]
family = "Iosevka NFM"
style = "Bold"

[font.bold_italic]
family = "Iosevka NFM"
style = "Bold Italic"

[font.italic]
family = "Iosevka NFM"
style = "Italic"

[font.normal]
family = "Iosevka NFM"
style = "Regular"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Shift|Control"

[mouse]
hide_when_typing = true
